### ISSUE TITLE
"Old PvP Plugins" Incompatibility 

### ISSUE THREAD

**Issue by Yronusa2000** [Voltariuss/ItemAttribute#1]
Salut,

Le plugin souffre d'un faille importante liée aux plugins d'ancien pvp.
J'utilise OldCombatMechanics et NoHitDelay (NoHitDelay permet de modifier le hit delay du serveur).

  Quand je frappe un joueur qui EST en hit delay (donc invincible), le coup est quand même compté. Par conséquent les effets parry, dodge, reflect s'appliquent...
Donc avec 10CPS et un ennemi qui a 10% de parade, il est quasiment sûr que l'effet va s'appliquer instantanément.

**Comment by Voltariuss** [comment]
Problème de priorité entre ItemAttribute et OldCombatMecanics, bug désormais fixé.
